!Project
build_configurations: [osl15-x86_64]
build_default_version: null
build_targets: [src/MulticamDatasetReader/utils, src/MulticamDatasetReader/core, src/tests]
builder: internal
lang: c++14
last_updated: 1636636028.710502
match_table: {XX: MDR, XXX: MULTICAMDATASETREADER, Xx: MDR, Xxx: MulticamDatasetReader,
  xx: mdr, xxx: multicamdatasetreader}
project_name: MulticamDatasetReader
project_short: MDR
version: 0.2.27
